name: GNP Mansion - 1882 -
favicon: null
layout_spectrum: 0.99378
typography_spectrum: 1
title: GNP Mansion - 1882 -
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdd7cd'
    - '#8fa1b3'
    - '#292a2f'
    - '#6f696a'
    - '#006ab5'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
